/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Laboratorio-Info
 */
public class Inicio_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_GUI
     */
    public Inicio_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Cadastrar_BTN = new javax.swing.JRadioButtonMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Calculadora_BTN = new javax.swing.JRadioButtonMenuItem();
        Bloco_BTN = new javax.swing.JCheckBoxMenuItem();
        Navegador_BTN = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Encerra_BTN = new javax.swing.JRadioButtonMenuItem();
        jMenu6 = new javax.swing.JMenu();
        Help_BTN = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jMenu1.setText("Cliente");

        Cadastrar_BTN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        Cadastrar_BTN.setSelected(true);
        Cadastrar_BTN.setText("Cadrastrar");
        Cadastrar_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icons8-ei-gatinha-50.png"))); // NOI18N
        Cadastrar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastrar_BTNActionPerformed(evt);
            }
        });
        jMenu1.add(Cadastrar_BTN);

        jMenu5.setText("Relatório");

        jRadioButtonMenuItem5.setSelected(true);
        jRadioButtonMenuItem5.setText("Cliente");
        jMenu5.add(jRadioButtonMenuItem5);

        jMenuItem1.setText("Produto");
        jMenu5.add(jMenuItem1);

        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Produto");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");
        jMenu2.add(jRadioButtonMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ferramentas");

        Calculadora_BTN.setSelected(true);
        Calculadora_BTN.setText("Calculadora");
        Calculadora_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calculadora_BTNActionPerformed(evt);
            }
        });
        jMenu3.add(Calculadora_BTN);

        Bloco_BTN.setSelected(true);
        Bloco_BTN.setText("Bloco de notas");
        Bloco_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bloco_BTNActionPerformed(evt);
            }
        });
        jMenu3.add(Bloco_BTN);

        Navegador_BTN.setText("Navegador");
        Navegador_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Navegador_BTNActionPerformed(evt);
            }
        });
        jMenu3.add(Navegador_BTN);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Sair");

        Encerra_BTN.setSelected(true);
        Encerra_BTN.setText("Encerrar");
        Encerra_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Encerra_BTNActionPerformed(evt);
            }
        });
        jMenu4.add(Encerra_BTN);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Ajuda");

        Help_BTN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        Help_BTN.setText("Help");
        Help_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Help_BTNActionPerformed(evt);
            }
        });
        jMenu6.add(Help_BTN);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Cadastrar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastrar_BTNActionPerformed
    JOptionPane.showMessageDialog (null, "Não Funcionando");
    }//GEN-LAST:event_Cadastrar_BTNActionPerformed

    private void Encerra_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Encerra_BTNActionPerformed
    System.exit(0);
    }//GEN-LAST:event_Encerra_BTNActionPerformed

    private void Calculadora_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calculadora_BTNActionPerformed
       try {
            Runtime.getRuntime().exec("cmd.exe /c start calc.exe ") ;
        } catch (IOException ex) {
        JOptionPane.showMessageDialog (null, "Não Funcionando");
        }
    }//GEN-LAST:event_Calculadora_BTNActionPerformed

    private void Bloco_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bloco_BTNActionPerformed
        try {
            Runtime.getRuntime().exec("cmd.exe /c start notepad.exe ") ;
        } catch (IOException ex) {
        JOptionPane.showMessageDialog (null, "Não Funcionando");
        }
    }//GEN-LAST:event_Bloco_BTNActionPerformed

    private void Help_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Help_BTNActionPerformed
    try {
            Runtime.getRuntime().exec("cmd.exe /c start C:\\HELP.pdf ") ;
        } catch (IOException ex) {
        JOptionPane.showMessageDialog (null, "Não Funcionando");
        }
    }//GEN-LAST:event_Help_BTNActionPerformed

    private void Navegador_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Navegador_BTNActionPerformed
    try {
            Runtime.getRuntime().exec("cmd.exe /c start chrome.exe www.term.ooo/") ;
        } catch (IOException ex) {
        JOptionPane.showMessageDialog (null, "Não Funcionando");
        }
    }//GEN-LAST:event_Navegador_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem Bloco_BTN;
    private javax.swing.JRadioButtonMenuItem Cadastrar_BTN;
    private javax.swing.JRadioButtonMenuItem Calculadora_BTN;
    private javax.swing.JRadioButtonMenuItem Encerra_BTN;
    private javax.swing.JMenuItem Help_BTN;
    private javax.swing.JMenuItem Navegador_BTN;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    // End of variables declaration//GEN-END:variables
}
